# Generated by Django 4.2.5 on 2023-09-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("subtitle", models.CharField(blank=True, default="", max_length=128)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LessonElement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_order", models.IntegerField()),
                ("text", models.TextField()),
                ("img_url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lessons.lesson")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("smc", "Single Multiple Choice"), ("mmc", "Multi Multiple Choice")],
                        default="smc",
                        max_length=32,
                    ),
                ),
                ("answers", models.ManyToManyField(related_name="answers", to="lessons.choice")),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lessons.quiz")),
            ],
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lessons.question"),
        ),
    ]
