# Generated by Django 4.2.5 on 2023-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_quizansweritem_quizanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonelement",
            name="type",
            field=models.CharField(choices=[("text", "Text"), ("image", "Image")], default="text", max_length=32),
        ),
    ]
