# Generated by Django 4.2.5 on 2023-09-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_lessonelement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonelement",
            name="lesson",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="lessons.lesson"),
            preserve_default=False,
        ),
    ]
