# Generated by Django 4.2.5 on 2023-09-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_lessonelement_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="img_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
