# Generated by Django 4.2.5 on 2023-09-27 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_choice_is_answer_choice_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answers",
        ),
    ]
