# Generated by Django 4.2.5 on 2023-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0009_quizanswer_total_quizanswer_total_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="percentage",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
